export const STORE_KEYS = {
  ACTIVE_CARD: 'activeCard',
  ACTIVE_BOARD: 'activeBoard',
  NEW_CARD: 'newCard',
}

export const ACTIONS = {
  CARD_CHANGED: 'CARD_CHANGED',
  CARD_CREATED: 'CARD_CREATED',
  BOARD_CREATED: 'BOARD_CREATED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
}
